
import type { Student, Teacher } from './definitions';

export const STUDENTS: Student[] = [
  {
    id: '1',
    fullName: 'Juan Pérez',
    dni: '40123456',
    cuil: '20-40123456-7',
    birthDate: '2006-05-10',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Homero Pérez', email: 'homero@example.com', phone: '1122334455' }, { name: 'Marge Pérez', email: 'marge@example.com', phone: '5544332211' }],
    entryYear: 2019,
    graduationYear: null,
    shift: 'Mañana',
    course: '5to',
    division: 'A',
    year: 5,
    orientation: 'Economia',
    grades: [{ courseYear: 4, actualYear: 2022, division: 'A', subject: 'Matemática-Ciclo Superior', grade: '8', book: 'L1', folio: 'F23' }, { courseYear: 4, actualYear: 2022, division: 'A', subject: 'Literatura', grade: '9', book: 'L1', folio: 'F24' }],
    isRegular: true,
  },
  {
    id: '2',
    fullName: 'Maria Garcia',
    dni: '41987654',
    cuil: '27-41987654-3',
    birthDate: '2005-11-22',
    birthPlace: 'Avellaneda',
    responsibles: [{ name: 'Carlos Garcia', email: 'carlos.g@example.com', phone: '3344556677' }],
    entryYear: 2018,
    graduationYear: 2023,
    shift: 'Tarde',
    course: 'Egresado',
    division: '',
    year: 6,
    orientation: 'Ciencias Naturales',
    grades: [{ courseYear: 6, actualYear: 2023, division: 'B', subject: 'Física Clásica y Moderna', grade: '10', book: 'L1', folio: 'F02' }, { courseYear: 6, actualYear: 2023, division: 'B', subject: 'Química del Carbono', grade: '9', book: 'L1', folio: 'F03' }],
    isRegular: false,
  },
  {
    id: '3',
    fullName: 'Carlos Rodriguez',
    dni: '42333444',
    cuil: '20-42333444-5',
    birthDate: '2007-02-15',
    birthPlace: 'Quilmes',
    responsibles: [{ name: 'Ricardo Rodriguez', email: 'ricardo@example.com', phone: '1234567890' }],
    entryYear: 2020,
    graduationYear: null,
    shift: 'Mañana',
    course: '4to',
    division: 'B',
    year: 4,
    grades: [{ courseYear: 3, actualYear: 2022, division: 'B', subject: 'Historia', grade: '7', book: 'L1', folio: 'F55' }],
    isRegular: false,
    orientation: 'Ciencias Sociales',
  },
  {
    id: '4',
    fullName: 'Ana Martínez',
    dni: '43123123',
    cuil: '27-43123123-8',
    birthDate: '2008-01-30',
    birthPlace: 'Lomas de Zamora',
    responsibles: [{ name: 'Laura Martínez', email: 'laura.m@example.com', phone: '2233445566' }],
    entryYear: 2021,
    graduationYear: null,
    shift: 'Tarde',
    course: '3ro',
    division: 'C',
    year: 3,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: true,
  },
  {
    id: '5',
    fullName: 'Luis Fernández',
    dni: '40555666',
    cuil: '20-40555666-1',
    birthDate: '2006-09-05',
    birthPlace: 'Berazategui',
    responsibles: [{ name: 'Jorge Fernández', email: 'jorge.f@example.com', phone: '4455667788' }],
    entryYear: 2019,
    graduationYear: null,
    shift: 'Mañana',
    course: '5to',
    division: 'A',
    year: 5,
    orientation: 'Arte',
    grades: [],
    isRegular: true,
  },
  {
    id: '6',
    fullName: 'Sofía González',
    dni: '42888777',
    cuil: '27-42888777-4',
    birthDate: '2007-07-12',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Marta González', email: 'marta.g@example.com', phone: '5566778899' }],
    entryYear: 2020,
    graduationYear: null,
    shift: 'Tarde',
    course: '4to',
    division: 'D',
    year: 4,
    orientation: 'Comunicacion',
    grades: [{ courseYear: 3, actualYear: 2022, division: 'D', subject: 'Biología', grade: '6', book: 'L2', folio: 'F11' }],
    isRegular: false,
  },
  {
    id: '7',
    fullName: 'Martín López',
    dni: '44111222',
    cuil: '20-44111222-9',
    birthDate: '2009-03-25',
    birthPlace: 'Ensenada',
    responsibles: [{ name: 'Roberto López', email: 'roberto.l@example.com', phone: '6677889900' }],
    entryYear: 2022,
    graduationYear: null,
    shift: 'Mañana',
    course: '2do',
    division: 'A',
    year: 2,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: true,
p  },
  {
    id: '8',
    fullName: 'Lucía Díaz',
    dni: '45001002',
    cuil: '27-45001002-5',
    birthDate: '2010-10-10',
    birthPlace: 'Berisso',
    responsibles: [{ name: 'Verónica Díaz', email: 'vero.d@example.com', phone: '7788990011' }],
    entryYear: 2023,
    graduationYear: null,
    shift: 'Tarde',
    course: '1ro',
    division: 'B',
    year: 1,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: true,
  },
  {
    id: '9',
    fullName: 'Mateo Sánchez',
    dni: '41234567',
    cuil: '20-41234567-2',
    birthDate: '2006-04-18',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Andrés Sánchez', email: 'andres.s@example.com', phone: '8899001122' }],
    entryYear: 2019,
    graduationYear: null,
    shift: 'Mañana',
    course: '5to',
    division: 'B',
    year: 5,
    orientation: 'Ciencias Naturales',
    grades: [],
    isRegular: true,
  },
  {
    id: '10',
    fullName: 'Valentina Romero',
    dni: '42765432',
    cuil: '27-42765432-6',
    birthDate: '2007-08-01',
    birthPlace: 'City Bell',
    responsibles: [{ name: 'Paula Romero', email: 'paula.r@example.com', phone: '9900112233' }],
    entryYear: 2020,
    graduationYear: null,
    shift: 'Tarde',
    course: '4to',
    division: 'C',
    year: 4,
    orientation: 'Turismo',
    grades: [],
    isRegular: false,
  },
  {
    id: '11',
    fullName: 'Agustín Gómez',
    dni: '43543210',
    cuil: '20-43543210-9',
    birthDate: '2008-06-14',
    birthPlace: 'Gonnet',
    responsibles: [{ name: 'Esteban Gómez', email: 'esteban.g@example.com', phone: '0011223344' }],
    entryYear: 2021,
    graduationYear: null,
    shift: 'Mañana',
    course: '3ro',
    division: 'A',
    year: 3,
    orientation: 'Ciclo Basico',
    grades: [{ courseYear: 2, actualYear: 2022, division: 'A', subject: 'Geografía', grade: '9', book: 'L3', folio: 'F40' }],
    isRegular: true,
  },
  {
    id: '12',
    fullName: 'Julieta Torres',
    dni: '44876543',
    cuil: '27-44876543-1',
    birthDate: '2009-12-03',
    birthPlace: 'Villa Elisa',
    responsibles: [{ name: 'Silvia Torres', email: 'silvia.t@example.com', phone: '1122334456' }],
    entryYear: 2022,
    graduationYear: null,
    shift: 'Tarde',
    course: '2do',
    division: 'D',
    year: 2,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: true,
  },
  {
    id: '13',
    fullName: 'Daniel Acosta',
    dni: '40112233',
    cuil: '20-40112233-4',
    birthDate: '2006-02-02',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Miguel Acosta', email: 'miguel.a@example.com', phone: '2233445567' }],
    entryYear: 2019,
    graduationYear: 2024,
    shift: 'Mañana',
    course: '6to',
    division: 'A',
    year: 6,
    orientation: 'Economia',
    grades: [],
    isRegular: true,
  },
  {
    id: '14',
    fullName: 'Camila Sosa',
    dni: '41998877',
    cuil: '27-41998877-0',
    birthDate: '2005-10-20',
    birthPlace: 'Berisso',
    responsibles: [{ name: 'Beatriz Sosa', email: 'beatriz.s@example.com', phone: '3344556678' }],
    entryYear: 2018,
    graduationYear: 2023,
    shift: 'Noche',
    course: 'Egresado',
    division: 'U',
    year: 3,
    orientation: 'Ciencias Sociales',
    grades: [],
    isRegular: false,
  },
  {
    id: '15',
    fullName: 'Facundo Ruiz',
    dni: '42445566',
    cuil: '20-42445566-8',
    birthDate: '2007-03-11',
    birthPlace: 'Ensenada',
    responsibles: [{ name: 'Gustavo Ruiz', email: 'gustavo.r@example.com', phone: '4455667789' }],
    entryYear: 2020,
    graduationYear: null,
    shift: 'Mañana',
    course: '4to',
    division: 'A',
    year: 4,
    orientation: 'Educacion Fisica',
    grades: [],
    isRegular: true,
  },
  {
    id: '16',
    fullName: 'Mía Benítez',
    dni: '43221133',
    cuil: '27-43221133-2',
    birthDate: '2008-11-08',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Clara Benítez', email: 'clara.b@example.com', phone: '5566778890' }],
    entryYear: 2021,
    graduationYear: null,
    shift: 'Tarde',
    course: '3ro',
    division: 'B',
    year: 3,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: true,
  },
  {
    id: '17',
    fullName: 'Thiago Medina',
    dni: '44665544',
    cuil: '20-44665544-7',
    birthDate: '2009-09-09',
    birthPlace: 'Los Hornos',
    responsibles: [{ name: 'Pablo Medina', email: 'pablo.m@example.com', phone: '6677889901' }],
    entryYear: 2022,
    graduationYear: null,
    shift: 'Mañana',
    course: '2do',
    division: 'C',
    year: 2,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: false,
  },
  {
    id: '18',
    fullName: 'Isabella Castillo',
    dni: '45123456',
    cuil: '27-45123456-9',
    birthDate: '2010-01-15',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Fernanda Castillo', email: 'fer.c@example.com', phone: '7788990012' }],
    entryYear: 2023,
    graduationYear: null,
    shift: 'Tarde',
    course: '1ro',
    division: 'A',
    year: 1,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: true,
  },
  {
    id: '19',
    fullName: 'Bautista Quiroga',
    dni: '40223344',
    cuil: '20-40223344-5',
    birthDate: '2006-07-21',
    birthPlace: 'Tolosa',
    responsibles: [{ name: 'Ramón Quiroga', email: 'ramon.q@example.com', phone: '8899001123' }],
    entryYear: 2019,
    graduationYear: 2024,
    shift: 'Noche',
    course: '3ro',
    division: 'U',
    year: 3,
    orientation: 'Lenguas Extranjeras',
    grades: [],
    isRegular: true,
  },
  {
    id: '20',
    fullName: 'Renata Flores',
    dni: '41876543',
    cuil: '27-41876543-2',
    birthDate: '2005-04-14',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Lorena Flores', email: 'lore.f@example.com', phone: '9900112234' }],
    entryYear: 2018,
    graduationYear: 2023,
    shift: 'Mañana',
    course: 'Egresado',
    division: '',
    year: 6,
    orientation: 'Arte',
    grades: [],
    isRegular: false,
  },
  {
    id: '21',
    fullName: 'Felipe Giménez',
    dni: '42777888',
    cuil: '20-42777888-0',
    birthDate: '2007-12-30',
    birthPlace: 'Ringuelet',
    responsibles: [{ name: 'Oscar Giménez', email: 'oscar.g@example.com', phone: '0011223345' }],
    entryYear: 2020,
    graduationYear: null,
    shift: 'Tarde',
    course: '4to',
    division: 'B',
    year: 4,
    orientation: 'Ciencias Naturales',
    grades: [],
    isRegular: true,
  },
  {
    id: '22',
    fullName: 'Emilia Herrera',
    dni: '43434343',
    cuil: '27-43434343-9',
    birthDate: '2008-02-28',
    birthPlace: 'San Carlos',
    responsibles: [{ name: 'Carolina Herrera', email: 'caro.h@example.com', phone: '1122334457' }],
    entryYear: 2021,
    graduationYear: null,
    shift: 'Mañana',
    course: '3ro',
    division: 'C',
    year: 3,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: true,
  },
  {
    id: '23',
    fullName: 'Tomás Morales',
    dni: '44555666',
    cuil: '20-44555666-1',
    birthDate: '2009-05-20',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Hugo Morales', email: 'hugo.m@example.com', phone: '2233445568' }],
    entryYear: 2022,
    graduationYear: null,
    shift: 'Tarde',
    course: '2do',
    division: 'B',
    year: 2,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: false,
  },
  {
    id: '24',
    fullName: 'Victoria Vera',
    dni: '45222333',
    cuil: '27-45222333-4',
    birthDate: '2010-03-03',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Julia Vera', email: 'julia.v@example.com', phone: '3344556679' }],
    entryYear: 2023,
    graduationYear: null,
    shift: 'Mañana',
    course: '1ro',
    division: 'D',
    year: 1,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: true,
  },
  {
    id: '25',
    fullName: 'Santino Vega',
    dni: '40333222',
    cuil: '20-40333222-6',
    birthDate: '2006-10-01',
    birthPlace: 'Berisso',
    responsibles: [{ name: 'Daniel Vega', email: 'daniel.v@example.com', phone: '4455667780' }],
    entryYear: 2019,
    graduationYear: 2024,
    shift: 'Tarde',
    course: '6to',
    division: 'B',
    year: 6,
    orientation: 'Ciencias Sociales',
    grades: [],
    isRegular: true,
  },
  {
    id: '26',
    fullName: 'Delfina Molina',
    dni: '41777666',
    cuil: '27-41777666-8',
    birthDate: '2005-01-25',
    birthPlace: 'Ensenada',
    responsibles: [{ name: 'Soledad Molina', email: 'sole.m@example.com', phone: '5566778891' }],
    entryYear: 2018,
    graduationYear: 2023,
    shift: 'Mañana',
    course: 'Egresado',
    division: '',
    year: 6,
    orientation: 'Economia',
    grades: [],
    isRegular: false,
  },
  {
    id: '27',
    fullName: 'Lorenzo Castro',
    dni: '42666555',
    cuil: '20-42666555-3',
    birthDate: '2007-06-06',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Fabián Castro', email: 'fabian.c@example.com', phone: '6677889902' }],
    entryYear: 2020,
    graduationYear: null,
    shift: 'Tarde',
    course: '4to',
    division: 'A',
    year: 4,
    orientation: 'Comunicacion',
    grades: [],
    isRegular: true,
  },
  {
    id: '28',
    fullName: 'Catalina Rivas',
    dni: '43333222',
    cuil: '27-43333222-7',
    birthDate: '2008-08-18',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Griselda Rivas', email: 'gris.r@example.com', phone: '7788990013' }],
    entryYear: 2021,
    graduationYear: null,
    shift: 'Mañana',
    course: '3ro',
    division: 'D',
    year: 3,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: true,
  },
  {
    id: '29',
    fullName: 'Joaquín Silva',
    dni: '44444333',
    cuil: '20-44444333-9',
    birthDate: '2009-04-23',
    birthPlace: 'City Bell',
    responsibles: [{ name: 'Leonardo Silva', email: 'leo.s@example.com', phone: '8899001124' }],
    entryYear: 2022,
    graduationYear: null,
    shift: 'Tarde',
    course: '2do',
    division: 'A',
    year: 2,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: false,
  },
  {
    id: '30',
    fullName: 'Olivia Luna',
    dni: '45333222',
    cuil: '27-45333222-1',
    birthDate: '2010-07-07',
    birthPlace: 'Gonnet',
    responsibles: [{ name: 'Marcela Luna', email: 'marce.l@example.com', phone: '9900112235' }],
    entryYear: 2023,
    graduationYear: null,
    shift: 'Mañana',
    course: '1ro',
    division: 'C',
    year: 1,
    orientation: 'Ciclo Basico',
    grades: [],
    isRegular: true,
  },
  {
    id: '31',
    fullName: 'Benjamín Navarro',
    dni: '40121212',
    cuil: '20-40121212-3',
    birthDate: '2006-11-11',
    birthPlace: 'La Plata',
    responsibles: [{ name: 'Sergio Navarro', email: 'sergio.n@example.com', phone: '0101232345' }],
    entryYear: 2019,
    graduationYear: 2024,
    shift: 'Tarde',
    course: '6to',
    division: 'A',
    year: 6,
    orientation: 'Arte',
    grades: [],
    isRegular: true,
  },
  {
    id: '32',
    fullName: 'Regina Ortiz',
    dni: '42585858',
    cuil: '27-42585858-2',
    birthDate: '2007-01-01',
    birthPlace: 'Ensenada',
    responsibles: [{ name: 'Mónica Ortiz', email: 'moni.o@example.com', phone: '2323454567' }],
    entryYear: 2020,
    graduationYear: null,
    shift: 'Noche',
    course: '2do',
    division: 'U',
    year: 2,
    orientation: 'Ciencias Sociales',
    grades: [],
    isRegular: false,
  }
];

export const TEACHERS: Teacher[] = [
  {
    id: 't1',
    fullName: 'Ana Martinez',
    dni: '25111222',
    cuil: '27-25111222-9',
    birthDate: '1985-08-20',
    birthPlace: 'Buenos Aires',
    abcEmail: 'ana.martinez@abc.gob.ar',
    altEmail: 'anamartinez@personal.com',
    phone: '1199887766',
    titles: ['Profesorado en Matemática', 'Licenciatura en Ciencias de la Educación'],
    registrationList: 'Listado Oficial',
    assignedCourses: [{ shift: 'Mañana', course: '5to A', schedule: 'Lunes 7:30-9:30', subject: 'Matemática' }, { shift: 'Mañana', course: '4to B', schedule: 'Martes 10:00-12:00', subject: 'Matemática' }],
  },
  {
    id: 't2',
    fullName: 'Roberto Sanchez',
    dni: '22888999',
    cuil: '20-22888999-1',
    birthDate: '1979-03-12',
    birthPlace: 'Córdoba',
    abcEmail: 'roberto.sanchez@abc.gob.ar',
    altEmail: 'robertos@provider.com',
    phone: '3511234567',
    titles: ['Profesorado en Lengua y Literatura'],
    registrationList: 'Listado 108 A',
    assignedCourses: [{ shift: 'Tarde', course: '2do C', schedule: 'Miércoles 13:30-15:30', subject: 'Lengua y Literatura' }, { shift: 'Tarde', course: '3ro A', schedule: 'Jueves 16:00-18:00', subject: 'Lengua y Literatura' }],
  },
  {
    id: 't3',
    fullName: 'Laura Gutiérrez',
    dni: '30123456',
    cuil: '27-30123456-7',
    birthDate: '1988-11-01',
    birthPlace: 'Rosario',
    abcEmail: 'laura.gutierrez@abc.gob.ar',
    altEmail: 'laurag@email.com',
    phone: '3419876543',
    titles: ['Profesorado de Historia'],
    registrationList: 'Listado Oficial',
    assignedCourses: [],
  },
  {
    id: 't4',
    fullName: 'Carlos Estévez',
    dni: '28765432',
    cuil: '20-28765432-5',
    birthDate: '1985-05-15',
    birthPlace: 'Mendoza',
    abcEmail: 'carlos.estevez@abc.gob.ar',
    altEmail: 'carlitos@email.com',
    phone: '2611239876',
    titles: ['Profesorado de Geografía'],
    registrationList: 'Listado 108 B',
    assignedCourses: [{ shift: 'Mañana', course: '1ro A', schedule: 'Viernes 8:00-10:00', subject: 'Geografía' }],
  },
  {
    id: 't5',
    fullName: 'Mariana Pizarro',
    dni: '32456789',
    cuil: '27-32456789-3',
    birthDate: '1990-02-20',
    birthPlace: 'La Plata',
    abcEmail: 'mariana.pizarro@abc.gob.ar',
    altEmail: 'mar.pizarro@email.com',
    phone: '2216543210',
    titles: ['Profesorado de Inglés', 'Traductorado Público'],
    registrationList: 'Listado Oficial',
    assignedCourses: [{ shift: 'Tarde', course: '4to C', schedule: 'Lunes 14:00-16:00', subject: 'Inglés' }, { shift: 'Tarde', course: '5to D', schedule: 'Miércoles 16:00-18:00', subject: 'Inglés' }],
  },
  {
    id: 't6',
    fullName: 'Jorge Dominguez',
    dni: '26543210',
    cuil: '20-26543210-8',
    birthDate: '1982-09-10',
    birthPlace: 'Mar del Plata',
    abcEmail: 'jorge.dominguez@abc.gob.ar',
    altEmail: 'jorged@email.com',
    phone: '2234567890',
    titles: ['Profesorado de Biología'],
    registrationList: 'Listado FINES',
    assignedCourses: [],
  },
  {
    id: 't7',
    fullName: 'Verónica Luna',
    dni: '31987654',
    cuil: '27-31987654-1',
    birthDate: '1989-07-25',
    birthPlace: 'Bahía Blanca',
    abcEmail: 'veronica.luna@abc.gob.ar',
    altEmail: 'veroluna@email.com',
    phone: '2918765432',
    titles: ['Licenciatura en Química', 'Profesorado en Fisicoquímica'],
    registrationList: 'Listado 108 A',
    assignedCourses: [{ shift: 'Mañana', course: '3ro B', schedule: 'Jueves 9:00-11:00', subject: 'Fisicoquímica' }],
  },
  {
    id: 't8',
    fullName: 'Hernán Crespo',
    dni: '24123789',
    cuil: '20-24123789-6',
    birthDate: '1980-04-05',
    birthPlace: 'La Plata',
    abcEmail: 'hernan.crespo@abc.gob.ar',
    altEmail: 'hernan.c@email.com',
    phone: '2217894561',
    titles: ['Profesorado de Educación Física'],
    registrationList: 'Listado Oficial',
    assignedCourses: [{ shift: 'Tarde', course: 'Todos', schedule: 'Lunes a Viernes', subject: 'Educación Física' }],
  },
  {
    id: 't9',
    fullName: 'Silvia Rojas',
    dni: '29876123',
    cuil: '27-29876123-4',
    birthDate: '1987-12-30',
    birthPlace: 'Tandil',
    abcEmail: 'silvia.rojas@abc.gob.ar',
    altEmail: 'sil.rojas@email.com',
    phone: '2491236547',
    titles: ['Profesorado de Artes Visuales'],
    registrationList: 'Listado 108 B In-Fine',
    assignedCourses: [],
  },
  {
    id: 't10',
    fullName: 'Diego Milito',
    dni: '27654987',
    cuil: '20-27654987-2',
    birthDate: '1984-06-18',
    birthPlace: 'Avellaneda',
    abcEmail: 'diego.milito@abc.gob.ar',
    altEmail: 'd.milito@email.com',
    phone: '1123459876',
    titles: ['Licenciatura en Economía', 'Contador Público'],
    registrationList: 'Listado de Difícil Cobertura',
    assignedCourses: [{ shift: 'Noche', course: '3ro U', schedule: 'Martes y Jueves 19:00-21:00', subject: 'Proyectos Organizacionales' }],
  },
  {
    id: 't11',
    fullName: 'Mónica Aguirre',
    dni: '23987654',
    cuil: '27-23987654-9',
    birthDate: '1979-01-22',
    birthPlace: 'La Plata',
    abcEmail: 'monica.aguirre@abc.gob.ar',
    altEmail: 'moni.a@email.com',
    phone: '2215554433',
    titles: ['Profesorado de Filosofía', 'Licenciatura en Psicología'],
    registrationList: 'Listado Oficial',
    assignedCourses: [{ shift: 'Mañana', course: '6to A', schedule: 'Miércoles 10:00-12:00', subject: 'Filosofía' }],
  },
  {
    id: 't12',
    fullName: 'Javier Zanetti',
    dni: '25888777',
    cuil: '20-25888777-3',
    birthDate: '1982-08-10',
    birthPlace: 'Lanús',
    abcEmail: 'javier.zanetti@abc.gob.ar',
    altEmail: 'pupi.z@email.com',
    phone: '1166778899',
    titles: ['Profesorado en Ciencias Jurídicas'],
    registrationList: 'Listado 108 A',
    assignedCourses: [{ shift: 'Tarde', course: '5to D', schedule: 'Viernes 14:00-16:00', subject: 'Derecho' }],
  },
  {
    id: 't13',
    fullName: 'Gabriela Sabatini',
    dni: '22777666',
    cuil: '27-22777666-5',
    birthDate: '1978-05-16',
    birthPlace: 'Buenos Aires',
    abcEmail: 'gabriela.sabatini@abc.gob.ar',
    altEmail: 'gaby.saba@email.com',
    phone: '1111223344',
    titles: ['Profesorado de Educación Física'],
    registrationList: 'Listado Oficial',
    assignedCourses: [],
  },
  {
    id: 't14',
    fullName: 'Ricardo Bochini',
    dni: '20111222',
    cuil: '20-20111222-9',
    birthDate: '1975-01-25',
    birthPlace: 'Zárate',
    abcEmail: 'ricardo.bochini@abc.gob.ar',
    altEmail: 'bocha@email.com',
    phone: '1187654321',
    titles: ['Licenciatura en Comunicación Social'],
    registrationList: 'Listado 108 B',
    assignedCourses: [{ shift: 'Tarde', course: '4to D', schedule: 'Martes 15:00-17:00', subject: 'Comunicación, Cultura y Sociedad' }],
  },
  {
    id: 't15',
    fullName: 'Mercedes Sosa',
    dni: '18999888',
    cuil: '27-18999888-4',
    birthDate: '1970-07-09',
    birthPlace: 'Tucumán',
    abcEmail: 'mercedes.sosa@abc.gob.ar',
    altEmail: 'negra.sosa@email.com',
    phone: '3814561237',
    titles: ['Profesorado de Música (Canto)'],
    registrationList: 'Listado Artística',
    assignedCourses: [{ shift: 'Mañana', course: '2do A', schedule: 'Lunes 9:00-11:00', subject: 'Educación Artística' }],
  },
  {
    id: 't16',
    fullName: 'René Favaloro',
    dni: '15123123',
    cuil: '20-15123123-2',
    birthDate: '1965-07-12',
    birthPlace: 'La Plata',
    abcEmail: 'rene.favaloro@abc.gob.ar',
    altEmail: 'dr.favaloro@email.com',
    phone: '2213216549',
    titles: ['Médico', 'Cardiocirujano'],
    registrationList: 'Listado de Emergencia',
    assignedCourses: [{ shift: 'Tarde', course: '4to B', schedule: 'Miércoles 14:00-16:00', subject: 'Salud y Adolescencia' }],
  },
  {
    id: 't17',
    fullName: 'Juana Azurduy',
    dni: '10111222',
    cuil: '27-10111222-6',
    birthDate: '1960-03-08',
    birthPlace: 'Salta',
    abcEmail: 'juana.azurduy@abc.gob.ar',
    altEmail: 'juanita@email.com',
    phone: '3879873216',
    titles: ['Profesora de Historia'],
    registrationList: 'Listado Oficial',
    assignedCourses: [{ shift: 'Noche', course: '1ro U', schedule: 'Lunes 19:00-21:00', subject: 'Ciencias Sociales' }],
  },
  {
    id: 't18',
    fullName: 'José de San Martín',
    dni: '05123456',
    cuil: '20-05123456-1',
    birthDate: '1955-02-25',
    birthPlace: 'Yapeyú',
    abcEmail: 'jose.sanmartin@abc.gob.ar',
    altEmail: 'el.libertador@email.com',
    phone: '1117781812',
    titles: ['Licenciado en Estrategia', 'Profesor de Historia'],
    registrationList: 'Listado Oficial',
    assignedCourses: [],
  },
  {
    id: 't19',
    fullName: 'Alicia Moreau',
    dni: '12987345',
    cuil: '27-12987345-0',
    birthDate: '1962-10-11',
    birthPlace: 'Buenos Aires',
    abcEmail: 'alicia.moreau@abc.gob.ar',
    altEmail: 'ali.moreau@email.com',
    phone: '1119861982',
    titles: ['Médica', 'Profesora de Biología'],
    registrationList: 'Listado 108 A',
    assignedCourses: [{ shift: 'Mañana', course: '5to B', schedule: 'Martes 8:00-10:00', subject: 'Biología, Genética y Sociedad' }],
  },
  {
    id: 't20',
    fullName: 'Mariano Moreno',
    dni: '08123789',
    cuil: '20-08123789-5',
    birthDate: '1958-09-23',
    birthPlace: 'Buenos Aires',
    abcEmail: 'mariano.moreno@abc.gob.ar',
    altEmail: 'marianito.m@email.com',
    phone: '1118101811',
    titles: ['Abogado', 'Profesor en Construcción de Ciudadanía'],
    registrationList: 'Listado de Difícil Cobertura',
    assignedCourses: [{ shift: 'Tarde', course: '2do C', schedule: 'Viernes 15:00-17:00', subject: 'Construcción de Ciudadanía' }],
  },
  {
    id: 't21',
    fullName: 'Eva Perón',
    dni: '16999888',
    cuil: '27-16999888-2',
    birthDate: '1968-05-07',
    birthPlace: 'Los Toldos',
    abcEmail: 'eva.peron@abc.gob.ar',
    altEmail: 'evita.p@email.com',
    phone: '1119451952',
    titles: ['Técnica en Políticas Sociales'],
    registrationList: 'Listado 108 B In-Fine',
    assignedCourses: [{ shift: 'Noche', course: '2do U', schedule: 'Miércoles 20:00-22:00', subject: 'Trabajo y Ciudadanía' }],
  },
  {
    id: 't22',
    fullName: 'Manuel Belgrano',
    dni: '06543210',
    cuil: '20-06543210-4',
    birthDate: '1956-06-03',
    birthPlace: 'Buenos Aires',
    abcEmail: 'manuel.belgrano@abc.gob.ar',
    altEmail: 'manu.belgrano@email.com',
    phone: '1118121820',
    titles: ['Abogado', 'Economista'],
    registrationList: 'Listado Oficial',
    assignedCourses: [],
  },
  {
    id: 't23',
    fullName: 'Julio Cortázar',
    dni: '14123123',
    cuil: '20-14123123-7',
    birthDate: '1964-08-26',
    birthPlace: 'Bélgica',
    abcEmail: 'julio.cortazar@abc.gob.ar',
    altEmail: 'cronopio.jc@email.com',
    phone: '1119141984',
    titles: ['Profesor de Literatura', 'Escritor'],
    registrationList: 'Listado Artística',
    assignedCourses: [{ shift: 'Mañana', course: '6to A', schedule: 'Jueves 8:00-10:00', subject: 'Literatura' }],
  },
  {
    id: 't24',
    fullName: 'Jorge Luis Borges',
    dni: '09876543',
    cuil: '20-09876543-9',
    birthDate: '1959-08-24',
    birthPlace: 'Buenos Aires',
    abcEmail: 'jorge.borges@abc.gob.ar',
    altEmail: 'georgie.b@email.com',
    phone: '1118991986',
    titles: ['Profesor de Literatura Inglesa', 'Escritor'],
    registrationList: 'Listado Oficial',
    assignedCourses: [],
  },
  {
    id: 't25',
    fullName: 'Astor Piazzolla',
    dni: '17654321',
    cuil: '20-17654321-8',
    birthDate: '1969-03-11',
    birthPlace: 'Mar del Plata',
    abcEmail: 'astor.piazzolla@abc.gob.ar',
    altEmail: 'astor.p@email.com',
    phone: '22319211992',
    titles: ['Músico', 'Bandoneonista', 'Compositor'],
    registrationList: 'Listado Artística',
    assignedCourses: [{ shift: 'Tarde', course: '3ro D', schedule: 'Lunes 16:00-18:00', subject: 'Educación Artística' }],
  },
  {
    id: 't26',
    fullName: 'Quino',
    dni: '19320717',
    cuil: '20-19320717-3',
    birthDate: '1972-07-17',
    birthPlace: 'Mendoza',
    abcEmail: 'quino.lavado@abc.gob.ar',
    altEmail: 'mafalda.quino@email.com',
    phone: '26119322020',
    titles: ['Dibujante', 'Humorista Gráfico'],
    registrationList: 'Listado Artística',
    assignedCourses: [],
  },
  {
    id: 't27',
    fullName: 'Lionel Messi',
    dni: '35123456',
    cuil: '20-35123456-8',
    birthDate: '1992-06-24',
    birthPlace: 'Rosario',
    abcEmail: 'lionel.messi@abc.gob.ar',
    altEmail: 'leo.messi@email.com',
    phone: '34119872022',
    titles: ['Técnico Deportivo', 'Entrenador de Fútbol'],
    registrationList: 'Listado de Emergencia',
    assignedCourses: [{ shift: 'Mañana', course: '4to A', schedule: 'Miércoles 9:00-11:00', subject: 'Educacion Fisica' }],
  },
  {
    id: 't28',
    fullName: 'Diego Maradona',
    dni: '26101960',
    cuil: '20-26101960-2',
    birthDate: '1982-10-30',
    birthPlace: 'Lanús',
    abcEmail: 'diego.maradona@abc.gob.ar',
    altEmail: 'd10s.maradona@email.com',
    phone: '1119602020',
    titles: ['Director Técnico'],
    registrationList: 'Listado de Emergencia',
    assignedCourses: [],
  },
  {
    id: 't29',
    fullName: 'Juan Manuel Fangio',
    dni: '10123456',
    cuil: '20-10123456-5',
    birthDate: '1961-06-24',
    birthPlace: 'Balcarce',
    abcEmail: 'juan.fangio@abc.gob.ar',
    altEmail: 'chueco.fangio@email.com',
    phone: '226619111995',
    titles: ['Técnico Mecánico', 'Instructor de Manejo'],
    registrationList: 'Listado 108 B',
    assignedCourses: [],
  },
  {
    id: 't30',
    fullName: 'Adolfo Pérez Esquivel',
    dni: '12111931',
    cuil: '20-12111931-9',
    birthDate: '1963-11-26',
    birthPlace: 'Buenos Aires',
    abcEmail: 'adolfo.esquivel@abc.gob.ar',
    altEmail: 'paz.esquivel@email.com',
    phone: '1119311980',
    titles: ['Arquitecto', 'Profesor de Construcción de Ciudadanía'],
    registrationList: 'Listado Oficial',
    assignedCourses: [{ shift: 'Tarde', course: '1ro B', schedule: 'Jueves 13:00-15:00', subject: 'Construcción de Ciudadanía' }],
  },
  {
    id: 't31',
    fullName: 'Leandro N. Alem',
    dni: '04123789',
    cuil: '20-04123789-0',
    birthDate: '1954-03-11',
    birthPlace: 'Buenos Aires',
    abcEmail: 'leandro.alem@abc.gob.ar',
    altEmail: 'ln.alem@email.com',
    phone: '1118421896',
    titles: ['Abogado', 'Profesor de Política y Ciudadanía'],
    registrationList: 'Listado 108 A',
    assignedCourses: [{ shift: 'Mañana', course: '5to C', schedule: 'Viernes 10:00-12:00', subject: 'Política y Ciudadanía' }],
  },
  {
    id: 't32',
    fullName: 'Ernesto Sabato',
    dni: '13123123',
    cuil: '20-13123123-6',
    birthDate: '1961-06-24',
    birthPlace: 'Rojas',
    abcEmail: 'ernesto.sabato@abc.gob.ar',
    altEmail: 'e.sabato@email.com',
    phone: '1119112011',
    titles: ['Físico', 'Escritor', 'Profesor de Literatura'],
    registrationList: 'Listado Oficial',
    assignedCourses: [],
  }
];
